services:
    client:
        build:
            context: .
            dockerfile: ./client/Dockerfile
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client/src/app
        entrypoint: ["npm", "start"]
        links:
            - api
        networks:
            - webappnetwork
    api:
        build:
            context: .
            dockerfile: ./api/Dockerfile
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ./api:/api
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge
